include(":ui:preventive-measures")
include(":ui:symptoms")
include(":core:dispatchers")
include(":core:main")
include(":core:usecase")
include(":ui:countries")
include(":ui:continents")
include(":lib:cases")
include(":core:domain-model")
include(":core:network")
include(":common-android")
include(":ui:home")
include(":app")
rootProject.name = "CoroNow"