include(":ui:countries")
include(":ui:continents")
include(":lib:cases")
include(":core:domain-model")
include(":core:network")
include(":core")
include(":common-android")
include(":ui:home")
include(":app")
rootProject.name = "CoroNow"