include(":coronow-stack:database")
include(":coronow-stack:local-repository")
include(":coronow-stack:remote-repository")
include(":coronow-stack:remote-graphql-repository")
include(":coronow-stack:usecase")
include(":ui:home")
include(":ui:preventive-measures")
include(":ui:symptoms")
include(":ui:countries")
include(":core:dispatchers")
include(":core:usecase")
include(":core:domain-model")
include(":core:network")
include(":core:base")
include(":common-android")
include(":app")
rootProject.name = "CoroNow"
